[package]
name = "core"
version = "0.0.1"
authors = ["Antoni Boucher <antoni.boucher@samsung.com>"]
description = "Dependency-free extension to the standard library"
repository = "https://github.com/adgear/mini-rs"
license = "MIT"
